VERSION="0.2.4"

BASE_API="https://corona.lmao.ninja"
API_TOTAL_ENDPOINT="$BASE_API/v3/covid-19/all"
API_ALL_COUNTRIES_ENDPOINT="$BASE_API/v3/covid-19/countries"
API_HISTORICAL_COUNTRIES_ENDPOINT="$BASE_API/v3/covid-19/historical"
